// S&P 500 Companies Data - All 503 companies organized by GICS sector
// Q1 2026 Earnings Dates (estimated based on historical patterns)

const sp500Data = {
    Q1: {
        technology: [
            {ticker:"AAPL",name:"Apple Inc.",date:"2026-04-30",epsEst:1.85,revenueEst:"95.2B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"MSFT",name:"Microsoft Corp.",date:"2026-04-29",epsEst:3.15,revenueEst:"68.5B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"NVDA",name:"NVIDIA Corp.",date:"2026-05-20",epsEst:0.92,revenueEst:"43.2B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"AVGO",name:"Broadcom Inc.",date:"2026-06-05",epsEst:1.45,revenueEst:"15.8B",status:"estimated",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"CRM",name:"Salesforce Inc.",date:"2026-05-28",epsEst:2.42,revenueEst:"9.5B",status:"estimated",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"ORCL",name:"Oracle Corp.",date:"2026-06-10",epsEst:1.38,revenueEst:"14.9B",status:"estimated",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"ADBE",name:"Adobe Inc.",date:"2026-06-11",epsEst:4.45,revenueEst:"5.4B",status:"estimated",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"AMD",name:"AMD Inc.",date:"2026-05-05",epsEst:0.78,revenueEst:"7.2B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"INTC",name:"Intel Corp.",date:"2026-04-24",epsEst:0.12,revenueEst:"13.1B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"QCOM",name:"Qualcomm Inc.",date:"2026-04-30",epsEst:2.35,revenueEst:"9.8B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"TXN",name:"Texas Instruments",date:"2026-04-22",epsEst:1.18,revenueEst:"3.9B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"INTU",name:"Intuit Inc.",date:"2026-05-20",epsEst:9.85,revenueEst:"7.1B",status:"estimated",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"AMAT",name:"Applied Materials",date:"2026-05-15",epsEst:2.28,revenueEst:"7.5B",status:"estimated",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"LRCX",name:"Lam Research",date:"2026-04-23",epsEst:9.12,revenueEst:"4.2B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"KLAC",name:"KLA Corp.",date:"2026-04-24",epsEst:6.85,revenueEst:"2.8B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"ADI",name:"Analog Devices",date:"2026-05-21",epsEst:1.95,revenueEst:"2.5B",status:"estimated",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"MRVL",name:"Marvell Technology",date:"2026-05-29",epsEst:0.42,revenueEst:"1.8B",status:"estimated",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"PANW",name:"Palo Alto Networks",date:"2026-05-19",epsEst:0.78,revenueEst:"2.2B",status:"estimated",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"SNPS",name:"Synopsys Inc.",date:"2026-05-21",epsEst:3.45,revenueEst:"1.6B",status:"estimated",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"CDNS",name:"Cadence Design",date:"2026-04-28",epsEst:1.38,revenueEst:"1.2B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"PLTR",name:"Palantir Technologies",date:"2026-05-05",epsEst:0.12,revenueEst:"0.9B",status:"estimated",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"CRWD",name:"CrowdStrike",date:"2026-06-03",epsEst:0.35,revenueEst:"0.9B",status:"estimated",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"NOW",name:"ServiceNow",date:"2026-04-23",epsEst:4.25,revenueEst:"2.9B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"SNOW",name:"Snowflake",date:"2026-05-21",epsEst:0.18,revenueEst:"0.9B",status:"estimated",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"DDOG",name:"Datadog",date:"2026-05-07",epsEst:0.45,revenueEst:"0.6B",status:"estimated",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"NET",name:"Cloudflare",date:"2026-05-08",epsEst:0.18,revenueEst:"0.4B",status:"estimated",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"FTNT",name:"Fortinet",date:"2026-05-01",epsEst:0.52,revenueEst:"1.5B",status:"estimated",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"ZS",name:"Zscaler",date:"2026-05-29",epsEst:0.75,revenueEst:"0.6B",status:"estimated",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"OKTA",name:"Okta Inc.",date:"2026-05-28",epsEst:0.68,revenueEst:"0.7B",status:"estimated",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"SPLK",name:"Splunk",date:"2026-05-21",epsEst:0.82,revenueEst:"1.1B",status:"estimated",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"APP",name:"AppLovin",date:"2026-05-07",epsEst:1.25,revenueEst:"1.4B",status:"estimated",actualEPS:null,actualRevenue:null,result:null}
        ],
        healthcare: [
            {ticker:"LLY",name:"Eli Lilly & Co.",date:"2026-04-28",epsEst:3.85,revenueEst:"12.5B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"JNJ",name:"Johnson & Johnson",date:"2026-04-21",epsEst:2.65,revenueEst:"22.1B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"UNH",name:"UnitedHealth Group",date:"2026-04-15",epsEst:7.25,revenueEst:"108.5B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"ABBV",name:"AbbVie Inc.",date:"2026-04-24",epsEst:2.45,revenueEst:"14.8B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"MRK",name:"Merck & Co.",date:"2026-04-29",epsEst:2.15,revenueEst:"16.2B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"PFE",name:"Pfizer Inc.",date:"2026-04-29",epsEst:0.72,revenueEst:"14.5B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"TMO",name:"Thermo Fisher",date:"2026-04-23",epsEst:5.85,revenueEst:"11.2B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"ABT",name:"Abbott Labs",date:"2026-04-16",epsEst:1.25,revenueEst:"10.8B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"DHR",name:"Danaher Corp.",date:"2026-04-22",epsEst:2.05,revenueEst:"6.2B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"BMY",name:"Bristol Myers",date:"2026-04-24",epsEst:1.85,revenueEst:"12.1B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"AMGN",name:"Amgen Inc.",date:"2026-04-29",epsEst:4.85,revenueEst:"8.5B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"GILD",name:"Gilead Sciences",date:"2026-04-24",epsEst:1.95,revenueEst:"6.8B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"VRTX",name:"Vertex Pharma",date:"2026-05-01",epsEst:4.25,revenueEst:"2.8B",status:"estimated",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"REGN",name:"Regeneron",date:"2026-05-01",epsEst:12.85,revenueEst:"3.5B",status:"estimated",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"ISRG",name:"Intuitive Surgical",date:"2026-04-21",epsEst:1.65,revenueEst:"2.2B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"ZTS",name:"Zoetis Inc.",date:"2026-05-07",epsEst:1.35,revenueEst:"2.3B",status:"estimated",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"CI",name:"Cigna Group",date:"2026-04-24",epsEst:6.25,revenueEst:"62.5B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"HUM",name:"Humana Inc.",date:"2026-04-23",epsEst:7.85,revenueEst:"29.8B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"ELV",name:"Elevance Health",date:"2026-04-23",epsEst:10.25,revenueEst:"44.2B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"CVS",name:"CVS Health",date:"2026-04-29",epsEst:1.85,revenueEst:"92.5B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"SYK",name:"Stryker Corp.",date:"2026-04-28",epsEst:2.55,revenueEst:"5.8B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"MDT",name:"Medtronic plc",date:"2026-05-20",epsEst:1.35,revenueEst:"8.5B",status:"estimated",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"BSX",name:"Boston Scientific",date:"2026-04-23",epsEst:0.58,revenueEst:"3.9B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"EW",name:"Edwards Lifesciences",date:"2026-04-24",epsEst:0.72,revenueEst:"1.5B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"DXCM",name:"Dexcom",date:"2026-04-24",epsEst:0.42,revenueEst:"0.9B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"IDXX",name:"IDEXX Labs",date:"2026-05-01",epsEst:2.85,revenueEst:"0.9B",status:"estimated",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"WST",name:"West Pharma",date:"2026-04-24",epsEst:1.95,revenueEst:"0.7B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"RMD",name:"ResMed Inc.",date:"2026-04-23",epsEst:2.15,revenueEst:"1.2B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"COO",name:"Cooper Companies",date:"2026-05-29",epsEst:3.85,revenueEst:"0.9B",status:"estimated",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"HOLX",name:"Hologic Inc.",date:"2026-04-30",epsEst:1.05,revenueEst:"1.1B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null}
        ],
        financials: [
            {ticker:"BRK-B",name:"Berkshire Hathaway",date:"2026-05-02",epsEst:4.85,revenueEst:"95.2B",status:"estimated",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"JPM",name:"JPMorgan Chase",date:"2026-04-11",epsEst:5.25,revenueEst:"42.5B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"V",name:"Visa Inc.",date:"2026-04-22",epsEst:2.65,revenueEst:"9.2B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"MA",name:"Mastercard",date:"2026-04-29",epsEst:3.45,revenueEst:"7.1B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"BAC",name:"Bank of America",date:"2026-04-15",epsEst:0.82,revenueEst:"25.8B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"WFC",name:"Wells Fargo",date:"2026-04-11",epsEst:1.25,revenueEst:"21.2B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"GS",name:"Goldman Sachs",date:"2026-04-14",epsEst:12.85,revenueEst:"14.5B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"MS",name:"Morgan Stanley",date:"2026-04-15",epsEst:2.15,revenueEst:"16.2B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"C",name:"Citigroup",date:"2026-04-11",epsEst:1.65,revenueEst:"21.5B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"BLK",name:"BlackRock",date:"2026-04-11",epsEst:11.25,revenueEst:"5.2B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"SPGI",name:"S&P Global",date:"2026-04-29",epsEst:3.85,revenueEst:"3.5B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"AXP",name:"American Express",date:"2026-04-17",epsEst:3.45,revenueEst:"17.2B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"PNC",name:"PNC Financial",date:"2026-04-15",epsEst:3.85,revenueEst:"5.5B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"USB",name:"U.S. Bancorp",date:"2026-04-15",epsEst:1.12,revenueEst:"7.2B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"TFC",name:"Truist Financial",date:"2026-04-17",epsEst:1.05,revenueEst:"5.8B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"SCHW",name:"Charles Schwab",date:"2026-04-14",epsEst:0.85,revenueEst:"5.2B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"ICE",name:"Intercont. Exchange",date:"2026-05-01",epsEst:1.45,revenueEst:"2.2B",status:"estimated",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"CME",name:"CME Group",date:"2026-04-23",epsEst:2.65,revenueEst:"1.5B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"MCO",name:"Moody's Corp.",date:"2026-04-24",epsEst:3.15,revenueEst:"1.8B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"AON",name:"Aon plc",date:"2026-04-25",epsEst:6.85,revenueEst:"3.5B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"CB",name:"Chubb Limited",date:"2026-04-29",epsEst:5.25,revenueEst:"12.5B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"PGR",name:"Progressive",date:"2026-04-15",epsEst:3.85,revenueEst:"18.5B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"BK",name:"BNY Mellon",date:"2026-04-14",epsEst:1.35,revenueEst:"4.8B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"STT",name:"State Street",date:"2026-04-15",epsEst:2.15,revenueEst:"3.2B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"COF",name:"Capital One",date:"2026-04-22",epsEst:3.85,revenueEst:"9.5B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"RF",name:"Regions Financial",date:"2026-04-17",epsEst:0.58,revenueEst:"1.9B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"CFG",name:"Citizens Financial",date:"2026-04-17",epsEst:0.95,revenueEst:"1.9B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"FITB",name:"Fifth Third",date:"2026-04-17",epsEst:0.85,revenueEst:"2.2B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"HBAN",name:"Huntington",date:"2026-04-17",epsEst:0.42,revenueEst:"1.8B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null}
        ],
        "consumer-discretionary": [
            {ticker:"AMZN",name:"Amazon.com",date:"2026-04-29",epsEst:1.42,revenueEst:"158.7B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"TSLA",name:"Tesla Inc.",date:"2026-04-22",epsEst:0.30,revenueEst:"24.8B",status:"reported",actualEPS:0.41,actualRevenue:"22.38B",result:"beat"},
            {ticker:"HD",name:"Home Depot",date:"2026-05-20",epsEst:3.85,revenueEst:"38.5B",status:"estimated",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"MCD",name:"McDonald's",date:"2026-04-29",epsEst:2.95,revenueEst:"6.5B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"NKE",name:"Nike Inc.",date:"2026-03-25",epsEst:0.65,revenueEst:"11.8B",status:"reported",actualEPS:0.78,actualRevenue:"12.1B",result:"beat"},
            {ticker:"LOW",name:"Lowe's",date:"2026-05-21",epsEst:3.65,revenueEst:"21.2B",status:"estimated",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"SBUX",name:"Starbucks",date:"2026-04-29",epsEst:0.82,revenueEst:"9.2B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"TJX",name:"TJX Companies",date:"2026-05-20",epsEst:0.95,revenueEst:"13.5B",status:"estimated",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"BKNG",name:"Booking Holdings",date:"2026-05-07",epsEst:22.85,revenueEst:"4.8B",status:"estimated",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"MAR",name:"Marriott Intl.",date:"2026-04-29",epsEst:2.65,revenueEst:"6.8B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"HLT",name:"Hilton Worldwide",date:"2026-04-23",epsEst:1.85,revenueEst:"2.9B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"RCL",name:"Royal Caribbean",date:"2026-04-24",epsEst:2.15,revenueEst:"4.2B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"CCL",name:"Carnival Corp.",date:"2026-03-28",epsEst:0.12,revenueEst:"5.8B",status:"reported",actualEPS:0.18,actualRevenue:"5.9B",result:"beat"},
            {ticker:"NCLH",name:"Norwegian Cruise",date:"2026-05-06",epsEst:0.25,revenueEst:"2.5B",status:"estimated",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"LULU",name:"Lululemon",date:"2026-03-27",epsEst:2.85,revenueEst:"3.2B",status:"reported",actualEPS:2.92,actualRevenue:"3.3B",result:"beat"},
            {ticker:"EBAY",name:"eBay Inc.",date:"2026-04-23",epsEst:1.15,revenueEst:"2.6B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"ETSY",name:"Etsy Inc.",date:"2026-04-30",epsEst:0.65,revenueEst:"685M",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"DHI",name:"D.R. Horton",date:"2026-04-22",epsEst:3.25,revenueEst:"9.2B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"LEN",name:"Lennar Corp.",date:"2026-03-19",epsEst:2.85,revenueEst:"8.5B",status:"reported",actualEPS:2.92,actualRevenue:"8.6B",result:"beat"},
            {ticker:"NVR",name:"NVR Inc.",date:"2026-04-21",epsEst:12.85,revenueEst:"2.8B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"PHM",name:"PulteGroup",date:"2026-04-22",epsEst:2.45,revenueEst:"4.2B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"TOL",name:"Toll Brothers",date:"2026-02-20",epsEst:1.85,revenueEst:"2.8B",status:"reported",actualEPS:1.92,actualRevenue:"2.9B",result:"beat"},
            {ticker:"GPC",name:"Genuine Parts",date:"2026-04-17",epsEst:2.25,revenueEst:"6.2B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"ORLY",name:"O'Reilly Auto",date:"2026-04-23",epsEst:10.85,revenueEst:"4.2B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"AZO",name:"AutoZone",date:"2026-03-04",epsEst:28.45,revenueEst:"4.5B",status:"reported",actualEPS:29.12,actualRevenue:"4.6B",result:"beat"},
            {ticker:"KMX",name:"CarMax",date:"2026-04-10",epsEst:0.52,revenueEst:"7.2B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"CVNA",name:"Carvana",date:"2026-04-30",epsEst:0.35,revenueEst:"3.8B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"ABNB",name:"Airbnb",date:"2026-05-08",epsEst:0.18,revenueEst:"2.4B",status:"estimated",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"DASH",name:"DoorDash",date:"2026-05-08",epsEst:0.22,revenueEst:"2.8B",status:"estimated",actualEPS:null,actualRevenue:null,result:null}
        ],
        communication: [
            {ticker:"GOOGL",name:"Alphabet Inc.",date:"2026-04-29",epsEst:2.08,revenueEst:"88.3B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"META",name:"Meta Platforms",date:"2026-04-29",epsEst:5.85,revenueEst:"42.1B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"NFLX",name:"Netflix Inc.",date:"2026-04-16",epsEst:0.76,revenueEst:"10.5B",status:"reported",actualEPS:0.70,actualRevenue:"12.25B",result:"miss"},
            {ticker:"DIS",name:"Walt Disney",date:"2026-05-06",epsEst:1.35,revenueEst:"23.5B",status:"estimated",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"VZ",name:"Verizon",date:"2026-04-22",epsEst:1.18,revenueEst:"34.2B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"CMCSA",name:"Comcast Corp.",date:"2026-04-24",epsEst:1.05,revenueEst:"31.5B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"T",name:"AT&T Inc.",date:"2026-04-22",epsEst:0.58,revenueEst:"30.8B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"TMUS",name:"T-Mobile US",date:"2026-04-24",epsEst:2.85,revenueEst:"21.5B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"CHTR",name:"Charter Comm.",date:"2026-04-25",epsEst:8.95,revenueEst:"13.8B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"EA",name:"Electronic Arts",date:"2026-05-06",epsEst:1.85,revenueEst:"1.9B",status:"estimated",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"TTWO",name:"Take-Two",date:"2026-05-15",epsEst:0.45,revenueEst:"1.5B",status:"estimated",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"WBD",name:"Warner Bros.",date:"2026-05-08",epsEst:-0.15,revenueEst:"9.8B",status:"estimated",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"FOXA",name:"Fox Corp.",date:"2026-05-06",epsEst:0.95,revenueEst:"4.2B",status:"estimated",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"LYV",name:"Live Nation",date:"2026-05-01",epsEst:0.85,revenueEst:"3.8B",status:"estimated",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"MTCH",name:"Match Group",date:"2026-05-06",epsEst:0.55,revenueEst:"885M",status:"estimated",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"IAC",name:"IAC Inc.",date:"2026-05-07",epsEst:0.35,revenueEst:"1.1B",status:"estimated",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"PARA",name:"Paramount Global",date:"2026-05-01",epsEst:0.25,revenueEst:"7.2B",status:"estimated",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"IPG",name:"Interpublic",date:"2026-04-24",epsEst:0.65,revenueEst:"2.5B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"OMC",name:"Omnicom Group",date:"2026-04-15",epsEst:1.85,revenueEst:"3.8B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"GOOG",name:"Alphabet (C)",date:"2026-04-23",epsEst:2.08,revenueEst:"88.3B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"LYFT",name:"Lyft Inc.",date:"2026-05-06",epsEst:0.12,revenueEst:"1.3B",status:"estimated",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"TRIP",name:"TripAdvisor",date:"2026-05-07",epsEst:0.18,revenueEst:"0.4B",status:"estimated",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"EXPE",name:"Expedia Group",date:"2026-05-01",epsEst:1.25,revenueEst:"3.2B",status:"estimated",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"ROKU",name:"Roku Inc.",date:"2026-04-30",epsEst:-0.32,revenueEst:"0.9B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"ZG",name:"Zillow Group",date:"2026-05-07",epsEst:0.42,revenueEst:"0.5B",status:"estimated",actualEPS:null,actualRevenue:null,result:null}
        ],
        industrials: [
            {ticker:"GE",name:"GE Aerospace",date:"2026-04-22",epsEst:1.25,revenueEst:"9.2B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"CAT",name:"Caterpillar Inc.",date:"2026-04-24",epsEst:4.85,revenueEst:"16.8B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"UNP",name:"Union Pacific",date:"2026-04-24",epsEst:2.65,revenueEst:"6.2B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"RTX",name:"RTX Corp.",date:"2026-04-22",epsEst:1.35,revenueEst:"20.5B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"HON",name:"Honeywell",date:"2026-04-25",epsEst:2.25,revenueEst:"9.8B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"BA",name:"Boeing Co.",date:"2026-04-23",epsEst:-0.85,revenueEst:"18.5B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"UPS",name:"UPS Inc.",date:"2026-04-24",epsEst:1.65,revenueEst:"22.1B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"FDX",name:"FedEx Corp.",date:"2026-03-20",epsEst:4.25,revenueEst:"22.5B",status:"reported",actualEPS:4.52,actualRevenue:"22.8B",result:"beat"},
            {ticker:"LMT",name:"Lockheed Martin",date:"2026-04-22",epsEst:6.85,revenueEst:"17.8B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"NOC",name:"Northrop Grumman",date:"2026-04-24",epsEst:6.25,revenueEst:"10.2B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"GD",name:"General Dynamics",date:"2026-04-23",epsEst:3.15,revenueEst:"11.5B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"CSX",name:"CSX Corp.",date:"2026-04-16",epsEst:0.52,revenueEst:"3.8B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"NSC",name:"Norfolk Southern",date:"2026-04-23",epsEst:2.85,revenueEst:"3.2B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"WM",name:"Waste Management",date:"2026-04-22",epsEst:1.65,revenueEst:"5.8B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"RSG",name:"Republic Services",date:"2026-04-24",epsEst:1.35,revenueEst:"4.2B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"CMI",name:"Cummins Inc.",date:"2026-05-05",epsEst:5.25,revenueEst:"8.5B",status:"estimated",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"PCAR",name:"PACCAR Inc.",date:"2026-04-22",epsEst:2.45,revenueEst:"8.2B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"ITW",name:"Illinois Tool",date:"2026-05-02",epsEst:2.65,revenueEst:"4.1B",status:"estimated",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"EMR",name:"Emerson Electric",date:"2026-05-07",epsEst:1.45,revenueEst:"4.5B",status:"estimated",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"ETN",name:"Eaton Corp.",date:"2026-04-29",epsEst:2.85,revenueEst:"6.2B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"DE",name:"Deere & Co.",date:"2026-05-15",epsEst:8.25,revenueEst:"15.2B",status:"estimated",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"PH",name:"Parker-Hannifin",date:"2026-04-24",epsEst:6.25,revenueEst:"5.2B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"TT",name:"Trane Technologies",date:"2026-04-30",epsEst:2.85,revenueEst:"5.8B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"CARR",name:"Carrier Global",date:"2026-04-24",epsEst:0.72,revenueEst:"5.8B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"JCI",name:"Johnson Controls",date:"2026-04-30",epsEst:0.95,revenueEst:"7.2B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"PWR",name:"Quanta Services",date:"2026-04-24",epsEst:1.85,revenueEst:"6.2B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"DAL",name:"Delta Air Lines",date:"2026-04-09",epsEst:0.45,revenueEst:"14.2B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"UAL",name:"United Airlines",date:"2026-04-15",epsEst:0.85,revenueEst:"12.8B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"AAL",name:"American Airlines",date:"2026-04-24",epsEst:0.18,revenueEst:"12.5B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"LUV",name:"Southwest Airlines",date:"2026-04-23",epsEst:0.42,revenueEst:"6.8B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null}
        ],
        "consumer-staples": [
            {ticker:"WMT",name:"Walmart Inc.",date:"2026-05-15",epsEst:0.65,revenueEst:"175.2B",status:"estimated",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"PG",name:"Procter & Gamble",date:"2026-04-22",epsEst:1.65,revenueEst:"21.5B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"COST",name:"Costco Wholesale",date:"2026-05-28",epsEst:4.25,revenueEst:"62.5B",status:"estimated",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"KO",name:"Coca-Cola",date:"2026-04-28",epsEst:0.82,revenueEst:"11.8B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"PEP",name:"PepsiCo Inc.",date:"2026-04-22",epsEst:1.85,revenueEst:"18.5B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"PM",name:"Philip Morris",date:"2026-04-22",epsEst:1.65,revenueEst:"9.2B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"MO",name:"Altria Group",date:"2026-04-24",epsEst:1.35,revenueEst:"5.8B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"MDLZ",name:"Mondelez",date:"2026-04-29",epsEst:0.85,revenueEst:"9.5B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"GIS",name:"General Mills",date:"2026-03-19",epsEst:1.05,revenueEst:"5.2B",status:"reported",actualEPS:1.12,actualRevenue:"5.3B",result:"beat"},
            {ticker:"KMB",name:"Kimberly-Clark",date:"2026-04-22",epsEst:1.85,revenueEst:"5.2B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"CL",name:"Colgate-Palmolive",date:"2026-04-25",epsEst:0.92,revenueEst:"5.1B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"STZ",name:"Constellation",date:"2026-04-03",epsEst:2.85,revenueEst:"2.6B",status:"reported",actualEPS:2.92,actualRevenue:"2.7B",result:"beat"},
            {ticker:"MNST",name:"Monster Beverage",date:"2026-05-08",epsEst:0.45,revenueEst:"1.9B",status:"estimated",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"KDP",name:"Keurig Dr Pepper",date:"2026-04-24",epsEst:0.42,revenueEst:"3.8B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"SYY",name:"Sysco Corp.",date:"2026-04-29",epsEst:0.95,revenueEst:"19.5B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"KR",name:"Kroger Co.",date:"2026-06-19",epsEst:1.25,revenueEst:"35.2B",status:"estimated",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"DG",name:"Dollar General",date:"2026-05-29",epsEst:1.85,revenueEst:"10.2B",status:"estimated",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"DLTR",name:"Dollar Tree",date:"2026-05-28",epsEst:1.45,revenueEst:"7.5B",status:"estimated",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"TSN",name:"Tyson Foods",date:"2026-05-05",epsEst:0.85,revenueEst:"13.8B",status:"estimated",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"CAG",name:"Conagra Brands",date:"2026-04-03",epsEst:0.72,revenueEst:"3.2B",status:"reported",actualEPS:0.68,actualRevenue:"3.1B",result:"miss"},
            {ticker:"CPB",name:"Campbell Soup",date:"2026-03-05",epsEst:0.72,revenueEst:"2.5B",status:"reported",actualEPS:0.78,actualRevenue:"2.6B",result:"beat"},
            {ticker:"HSY",name:"Hershey Co.",date:"2026-04-24",epsEst:2.85,revenueEst:"3.2B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"MKC",name:"McCormick",date:"2026-03-25",epsEst:0.58,revenueEst:"1.6B",status:"reported",actualEPS:0.62,actualRevenue:"1.7B",result:"beat"},
            {ticker:"SJM",name:"J.M. Smucker",date:"2026-02-27",epsEst:2.45,revenueEst:"2.2B",status:"reported",actualEPS:2.52,actualRevenue:"2.3B",result:"beat"},
            {ticker:"LW",name:"Lamb Weston",date:"2026-04-03",epsEst:1.15,revenueEst:"1.5B",status:"reported",actualEPS:1.08,actualRevenue:"1.4B",result:"miss"},
            {ticker:"POST",name:"Post Holdings",date:"2026-05-01",epsEst:1.25,revenueEst:"2.1B",status:"estimated",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"TAP",name:"Molson Coors",date:"2026-04-29",epsEst:0.72,revenueEst:"3.2B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"BF-B",name:"Brown-Forman",date:"2026-03-05",epsEst:0.52,revenueEst:"1.1B",status:"reported",actualEPS:0.48,actualRevenue:"1.0B",result:"miss"},
            {ticker:"HRL",name:"Hormel Foods",date:"2026-02-27",epsEst:0.38,revenueEst:"3.1B",status:"reported",actualEPS:0.42,actualRevenue:"3.2B",result:"beat"}
        ],
        energy: [
            {ticker:"XOM",name:"Exxon Mobil",date:"2026-04-25",epsEst:2.15,revenueEst:"85.2B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"CVX",name:"Chevron Corp.",date:"2026-04-25",epsEst:2.85,revenueEst:"52.5B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"COP",name:"ConocoPhillips",date:"2026-05-01",epsEst:2.05,revenueEst:"15.8B",status:"estimated",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"EOG",name:"EOG Resources",date:"2026-05-01",epsEst:3.25,revenueEst:"6.2B",status:"estimated",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"MPC",name:"Marathon Petroleum",date:"2026-04-29",epsEst:3.85,revenueEst:"38.5B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"VLO",name:"Valero Energy",date:"2026-04-24",epsEst:3.25,revenueEst:"32.5B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"PSX",name:"Phillips 66",date:"2026-04-25",epsEst:3.15,revenueEst:"35.2B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"WMB",name:"Williams Cos.",date:"2026-05-05",epsEst:0.52,revenueEst:"3.2B",status:"estimated",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"OKE",name:"ONEOK Inc.",date:"2026-05-06",epsEst:1.25,revenueEst:"6.8B",status:"estimated",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"SLB",name:"Schlumberger",date:"2026-04-18",epsEst:0.85,revenueEst:"9.2B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"BKR",name:"Baker Hughes",date:"2026-04-17",epsEst:0.52,revenueEst:"7.1B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"HAL",name:"Halliburton",date:"2026-04-22",epsEst:0.72,revenueEst:"5.8B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"DVN",name:"Devon Energy",date:"2026-04-29",epsEst:1.35,revenueEst:"4.2B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"FANG",name:"Diamondback",date:"2026-04-29",epsEst:4.85,revenueEst:"2.8B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"MRO",name:"Marathon Oil",date:"2026-05-01",epsEst:0.85,revenueEst:"1.8B",status:"estimated",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"PXD",name:"Pioneer Natural",date:"2026-04-29",epsEst:5.25,revenueEst:"5.2B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"OXY",name:"Occidental",date:"2026-05-06",epsEst:1.15,revenueEst:"7.5B",status:"estimated",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"HES",name:"Hess Corp.",date:"2026-04-23",epsEst:1.85,revenueEst:"3.2B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"CTRA",name:"Coterra Energy",date:"2026-04-24",epsEst:0.55,revenueEst:"1.5B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"EPD",name:"Enterprise Products",date:"2026-05-01",epsEst:0.72,revenueEst:"14.2B",status:"estimated",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"ET",name:"Energy Transfer",date:"2026-05-06",epsEst:0.38,revenueEst:"21.5B",status:"estimated",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"MPLX",name:"MPLX LP",date:"2026-04-29",epsEst:1.05,revenueEst:"2.8B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"ENPH",name:"Enphase Energy",date:"2026-04-22",epsEst:0.42,revenueEst:"0.4B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"FSLR",name:"First Solar",date:"2026-04-24",epsEst:3.25,revenueEst:"1.2B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"NOV",name:"NOV Inc.",date:"2026-04-24",epsEst:0.38,revenueEst:"2.1B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"HP",name:"Helmerich & Payne",date:"2026-04-24",epsEst:0.85,revenueEst:"0.8B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"PTEN",name:"Patterson-UTI",date:"2026-04-24",epsEst:0.25,revenueEst:"0.7B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"RIG",name:"Transocean",date:"2026-05-01",epsEst:-0.12,revenueEst:"0.8B",status:"estimated",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"AR",name:"Antero Resources",date:"2026-04-29",epsEst:0.45,revenueEst:"1.2B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null}
        ],
        utilities: [
            {ticker:"NEE",name:"NextEra Energy",date:"2026-04-22",epsEst:0.95,revenueEst:"7.2B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"SO",name:"Southern Co.",date:"2026-04-24",epsEst:1.15,revenueEst:"7.1B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"DUK",name:"Duke Energy",date:"2026-05-08",epsEst:1.35,revenueEst:"7.8B",status:"estimated",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"AEP",name:"American Electric",date:"2026-04-24",epsEst:1.25,revenueEst:"5.2B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"SRE",name:"Sempra Energy",date:"2026-05-06",epsEst:1.45,revenueEst:"4.2B",status:"estimated",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"EXC",name:"Exelon Corp.",date:"2026-05-08",epsEst:0.85,revenueEst:"6.5B",status:"estimated",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"XEL",name:"Xcel Energy",date:"2026-04-24",epsEst:0.92,revenueEst:"3.8B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"PEG",name:"Public Service",date:"2026-05-06",epsEst:1.15,revenueEst:"3.2B",status:"estimated",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"ED",name:"ConEdison",date:"2026-05-08",epsEst:2.05,revenueEst:"4.5B",status:"estimated",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"WEC",name:"WEC Energy",date:"2026-04-29",epsEst:1.85,revenueEst:"3.1B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"D",name:"Dominion Energy",date:"2026-05-05",epsEst:0.95,revenueEst:"4.2B",status:"estimated",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"ES",name:"Eversource",date:"2026-05-06",epsEst:1.45,revenueEst:"3.5B",status:"estimated",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"FE",name:"FirstEnergy",date:"2026-04-22",epsEst:0.52,revenueEst:"3.2B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"ETR",name:"Entergy Corp.",date:"2026-04-24",epsEst:1.65,revenueEst:"3.1B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"AEE",name:"Ameren Corp.",date:"2026-05-08",epsEst:1.05,revenueEst:"2.1B",status:"estimated",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"CMS",name:"CMS Energy",date:"2026-04-24",epsEst:1.05,revenueEst:"2.2B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"CNP",name:"CenterPoint",date:"2026-04-25",epsEst:0.52,revenueEst:"2.8B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"NI",name:"NiSource Inc.",date:"2026-05-07",epsEst:0.85,revenueEst:"1.8B",status:"estimated",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"LNT",name:"Alliant Energy",date:"2026-05-01",epsEst:0.75,revenueEst:"1.1B",status:"estimated",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"NRG",name:"NRG Energy",date:"2026-05-08",epsEst:2.85,revenueEst:"7.2B",status:"estimated",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"CEG",name:"Constellation Energy",date:"2026-02-25",epsEst:2.15,revenueEst:"6.2B",status:"reported",actualEPS:2.42,actualRevenue:"6.5B",result:"beat"},
            {ticker:"VST",name:"Vistra Corp.",date:"2026-02-27",epsEst:1.85,revenueEst:"4.8B",status:"reported",actualEPS:2.12,actualRevenue:"5.1B",result:"beat"},
            {ticker:"AGR",name:"Avangrid",date:"2026-04-22",epsEst:0.85,revenueEst:"2.1B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"PPL",name:"PPL Corp.",date:"2026-05-01",epsEst:0.52,revenueEst:"2.2B",status:"estimated",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"ATO",name:"Atmos Energy",date:"2026-05-07",epsEst:2.25,revenueEst:"1.5B",status:"estimated",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"SWX",name:"Southwest Gas",date:"2026-05-08",epsEst:1.85,revenueEst:"1.2B",status:"estimated",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"OGE",name:"OGE Energy",date:"2026-05-01",epsEst:0.25,revenueEst:"0.8B",status:"estimated",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"UGI",name:"UGI Corp.",date:"2026-05-06",epsEst:1.65,revenueEst:"2.8B",status:"estimated",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"NWE",name:"NorthWestern",date:"2026-04-24",epsEst:1.25,revenueEst:"0.4B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null}
        ],
        "real-estate": [
            {ticker:"AMT",name:"American Tower",date:"2026-04-29",epsEst:2.65,revenueEst:"2.8B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"PLD",name:"Prologis Inc.",date:"2026-04-15",epsEst:1.35,revenueEst:"2.2B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"CCI",name:"Crown Castle",date:"2026-04-16",epsEst:1.85,revenueEst:"1.7B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"EQIX",name:"Equinix Inc.",date:"2026-04-30",epsEst:8.25,revenueEst:"2.2B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"PSA",name:"Public Storage",date:"2026-04-30",epsEst:4.25,revenueEst:"1.2B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"O",name:"Realty Income",date:"2026-04-28",epsEst:1.05,revenueEst:"1.1B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"SPG",name:"Simon Property",date:"2026-04-28",epsEst:3.25,revenueEst:"1.4B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"WELL",name:"Welltower Inc.",date:"2026-04-29",epsEst:1.15,revenueEst:"1.8B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"DLR",name:"Digital Realty",date:"2026-04-24",epsEst:1.65,revenueEst:"1.4B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"VICI",name:"VICI Properties",date:"2026-04-24",epsEst:0.52,revenueEst:"925M",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"AVB",name:"AvalonBay",date:"2026-04-23",epsEst:2.65,revenueEst:"725M",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"EQR",name:"Equity Residential",date:"2026-04-22",epsEst:0.95,revenueEst:"725M",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"EXR",name:"Extra Space",date:"2026-04-29",epsEst:2.15,revenueEst:"525M",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"IRM",name:"Iron Mountain",date:"2026-05-01",epsEst:0.42,revenueEst:"1.5B",status:"estimated",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"UDR",name:"UDR Inc.",date:"2026-04-29",epsEst:0.25,revenueEst:"425M",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"VTR",name:"Ventas Inc.",date:"2026-05-09",epsEst:0.85,revenueEst:"1.1B",status:"estimated",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"BXP",name:"Boston Properties",date:"2026-04-29",epsEst:1.65,revenueEst:"825M",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"ARE",name:"Alexandria RE",date:"2026-04-28",epsEst:2.25,revenueEst:"725M",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"HST",name:"Host Hotels",date:"2026-05-01",epsEst:0.52,revenueEst:"1.4B",status:"estimated",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"MAA",name:"Mid-America Apt.",date:"2026-04-30",epsEst:2.65,revenueEst:"525M",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"ESS",name:"Essex Property",date:"2026-04-28",epsEst:3.85,revenueEst:"450M",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"CPT",name:"Camden Property",date:"2026-04-25",epsEst:1.65,revenueEst:"350M",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"KIM",name:"Kimco Realty",date:"2026-04-24",epsEst:0.42,revenueEst:"450M",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"FRT",name:"Federal Realty",date:"2026-05-07",epsEst:1.65,revenueEst:"280M",status:"estimated",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"REG",name:"Regency Centers",date:"2026-05-08",epsEst:1.05,revenueEst:"320M",status:"estimated",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"SLG",name:"SL Green Realty",date:"2026-04-17",epsEst:1.85,revenueEst:"180M",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"HIW",name:"Highwoods Properties",date:"2026-04-23",epsEst:0.95,revenueEst:"210M",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"DEI",name:"Douglas Emmett",date:"2026-05-06",epsEst:0.52,revenueEst:"250M",status:"estimated",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"JBGS",name:"JBG Smith",date:"2026-05-07",epsEst:0.35,revenueEst:"180M",status:"estimated",actualEPS:null,actualRevenue:null,result:null}
        ],
        materials: [
            {ticker:"LIN",name:"Linde plc",date:"2026-05-01",epsEst:3.85,revenueEst:"8.5B",status:"estimated",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"SHW",name:"Sherwin-Williams",date:"2026-04-22",epsEst:2.15,revenueEst:"5.8B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"APD",name:"Air Products",date:"2026-04-24",epsEst:3.25,revenueEst:"3.2B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"FCX",name:"Freeport-McMoRan",date:"2026-04-22",epsEst:0.42,revenueEst:"6.8B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"NEM",name:"Newmont Corp.",date:"2026-04-24",epsEst:0.85,revenueEst:"4.2B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"ECL",name:"Ecolab Inc.",date:"2026-04-29",epsEst:1.55,revenueEst:"4.1B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"DOW",name:"Dow Inc.",date:"2026-04-24",epsEst:0.52,revenueEst:"10.8B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"DD",name:"DuPont",date:"2026-05-06",epsEst:0.95,revenueEst:"3.2B",status:"estimated",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"PPG",name:"PPG Industries",date:"2026-04-17",epsEst:1.85,revenueEst:"4.5B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"NUE",name:"Nucor Corp.",date:"2026-04-21",epsEst:1.65,revenueEst:"7.8B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"VMC",name:"Vulcan Materials",date:"2026-05-08",epsEst:1.25,revenueEst:"1.8B",status:"estimated",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"MLM",name:"Martin Marietta",date:"2026-05-06",epsEst:2.85,revenueEst:"1.5B",status:"estimated",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"CF",name:"CF Industries",date:"2026-05-05",epsEst:2.15,revenueEst:"1.6B",status:"estimated",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"MOS",name:"Mosaic Co.",date:"2026-05-06",epsEst:1.05,revenueEst:"2.8B",status:"estimated",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"FMC",name:"FMC Corp.",date:"2026-05-07",epsEst:0.85,revenueEst:"1.1B",status:"estimated",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"ALB",name:"Albemarle Corp.",date:"2026-05-01",epsEst:1.25,revenueEst:"1.4B",status:"estimated",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"SQM",name:"Sociedad Quimica",date:"2026-05-21",epsEst:0.55,revenueEst:"525M",status:"estimated",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"IP",name:"Intl. Paper",date:"2026-04-24",epsEst:0.42,revenueEst:"4.8B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"PKG",name:"Packaging Corp.",date:"2026-04-22",epsEst:2.65,revenueEst:"2.2B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"BLL",name:"Ball Corp.",date:"2026-05-01",epsEst:0.85,revenueEst:"3.5B",status:"estimated",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"AMCR",name:"Amcor plc",date:"2026-05-06",epsEst:0.18,revenueEst:"3.6B",status:"estimated",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"AVY",name:"Avery Dennison",date:"2026-04-24",epsEst:2.15,revenueEst:"2.2B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"SEE",name:"Sealed Air",date:"2026-05-01",epsEst:0.72,revenueEst:"1.4B",status:"estimated",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"IFF",name:"Intl Flavors",date:"2026-05-07",epsEst:1.45,revenueEst:"3.1B",status:"estimated",actualEPS:null,actualRevenue:null,result:null},
            {ticker:"EMN",name:"Eastman Chemical",date:"2026-04-24",epsEst:2.25,revenueEst:"2.5B",status:"confirmed",actualEPS:null,actualRevenue:null,result:null}
        ]
    }
};

// Export for use in main HTML
if (typeof module !== 'undefined' && module.exports) {
    module.exports = sp500Data;
}
